export const MyLists = [
    {
        href: 'https://github.com/ono-hiroki',
        title: 'github \u2192',
        imageSrc: '/myLists/img.png',
        description: 'githubのアカウント。',
        tags: ['github'],
    },
    {
        href: 'https://www.instagram.com/ono_8931/',
        title: 'instagram \u2192',
        imageSrc: '/myLists/img_7.png',
        description: 'instagramのアカウント。折り紙と水彩画',
        tags: ['instagram'],
    },
    {
        href: '#',
        title: 'モデリングツール（仮）に満たないもの \u2192',
        imageSrc: '/myLists/img_1.png',
        description: 'お金ないので止めてる。モデリングツールをつくるためにreactflowを触ってみた。EC2にデプロイしてた。バックエンドはLaravel。',
        tags: ['React', 'TypeScript', 'reactflow', 'Laravel'],
    },
    {
        href: 'https://threejs-lp.vercel.app/',
        title: '回転 \u2192',
        imageSrc: '/myLists/img_5.png',
        description: 'threejsで回転させたもの',
        tags: ['three.js', 'vite'],
    },
    {
        href: 'https://room-alpha-three.vercel.app/',
        title: '部屋 \u2192',
        imageSrc: '/myLists/img_13.png',
        description: 'blenderで作ったオブジェクトをthreejsで表示させたもの',
        tags: ['three.js', 'vite', 'blender'],
    },
    {
        href: 'https://github.com/ono-hiroki/practice_laravel3',
        title: 'practice laravel \u2192',
        imageSrc: '/myLists/img_15.png',
        description: 'laravelでcrud機能の試し',
        tags: ['Lravel', 'mysql'],
    },
    {
        href: '/reactflow',
        title: 'reactflowの試し \u2192',
        imageSrc: '/myLists/img_9.png',
        description: 'three.jsで試した者たち',
        tags: ['まとめ'],
    },
    {
        href: 'https://entrance-eight.vercel.app/',
        title: '入り口 \u2192',
        imageSrc: '/myLists/img_14.png',
        description: 'threejs journeyを参考にしたもの',
        tags: ['three.js', 'vite'],
    },
    {
        href: 'https://classroom-green.vercel.app/',
        title: '教室 \u2192',
        imageSrc: '/myLists/img_11.png',
        description: 'sketchupで作ったオブジェクトをthreejsで表示させたもの',
        tags: ['three.js', 'vite', 'sketchup'],
    },
    {
        href: 'https://real-object-threejs.vercel.app/',
        title: 'realオブジェクト \u2192',
        imageSrc: '/myLists/img_2.png',
        description: 'threejsでオブジェクトをそれっぽく反射させたもの',
        tags: ['three.js', 'vite'],
    },
    {
        href: 'https://scroll-animation-website-black.vercel.app/',
        title: 'スクロールアニメーション \u2192',
        imageSrc: '/myLists/img_4.png',
        description: 'threejsでスクロールに合わせてオブジェクトを動かす',
        tags: ['three.js', 'vite'],
    },
    {
        href: '/ugomemo',
        title: '動くWebデザイン アイデア帳でサンプルを動かしてみた者たち \u2192',
        imageSrc: '/myLists/img_10.png',
        description: '動くWebデザイン アイデア帳のサンプルを動かしてみた者たち',
        tags: ['まとめ'],
    },
    {
        href: '/threejs',
        title: '3Dモデル系 \u2192',
        imageSrc: '/myLists/img_9.png',
        description: 'three.jsで試した者たち',
        tags: ['まとめ'],
    },
    {
        href: 'https://school-outside.vercel.app/',
        title: '学校 外 \u2192',
        imageSrc: '/myLists/img_12.png',
        description: 'sketchupで作ったオブジェクトをthreejsで表示させたもの',
        tags: ['three.js', 'vite', 'sketchup'],
    },


];
