export const MyLists = [
    {
        href: 'https://github.com/ono-hiroki',
        title: 'github \u2192',
        imageSrc: '/myLists/img.png',
        description: 'githubのアカウント。',
        tags: ['github'],
    },
    {
        href: 'https://www.instagram.com/ono_8931/',
        title: 'instagram \u2192',
        imageSrc: '/myLists/img_7.png',
        description: 'instagramのアカウント。',
        tags: ['instagram'],
    },
    {
        href: 'http://conticuwa.com/reactflow/edit',
        title: 'モデリングツール（仮）に満たないもの \u2192',
        imageSrc: '/myLists/img_1.png',
        description: 'モデリングツールをつくるためにreactflowを触ってみた。EC2にデプロイしてる。バックエンドはLaravel。もしかしたら止めてるかも',
        tags: ['React', 'TypeScript', 'reactflow', 'Laravel'],
    },
    {
        href: 'https://threejs-lp.vercel.app/',
        title: '回転 \u2192',
        imageSrc: '/myLists/img_5.png',
        description: 'threejsで回転させたもの',
        tags: ['three.js', 'vite'],
    },
    {
        href: 'https://real-object-threejs.vercel.app/',
        title: 'realオブジェクト \u2192',
        imageSrc: '/myLists/img_2.png',
        description: 'threejsでオブジェクトをそれっぽく反射させたもの',
        tags: ['three.js', 'vite'],
    },
    {
        href: 'https://scroll-animation-website-black.vercel.app/',
        title: 'スクロールアニメーション \u2192',
        imageSrc: '/myLists/img_4.png',
        description: 'threejsでスクロールに合わせてオブジェクトを動かす',
        tags: ['three.js', 'vite'],
    },
    {
        href: 'https://hono-ono-hiroki.vercel.app/web-site01',
        title: 'うごメモ \u2192',
        imageSrc: '/myLists/img_8.png',
        description: '動くWebデザイン アイディア帳のサンプルサイトをnext.jsで書き換えたもの',
        tags: ['js', 'next.js'],
    },
    {
        href: '/ugomemo',
        title: '動くWebデザイン アイデア帳でサンプルを動かしてみた者たち \u2192',
        imageSrc: '/myLists/img_3.png',
        description: '動くWebデザイン アイデア帳のサンプルを動かしてみた者たち',
        tags: ['まとめ'],
    },
    {
        href: '/threejs',
        title: '3Dモデル系 \u2192',
        imageSrc: '/myLists/img_9.png',
        description: 'three.jsを使った3Dモデル',
        tags: ['まとめ'],
    },

];
