const pathgroup = '/reactflow';

export const ReactFlowLists = [
    {
        href: `${pathgroup}/AddNodeOnEdgeDrop`,
        title: 'AddNodeOnEdgeDrop \u2192',
        imageSrc: '/reactflow/img.png',
        description: 'reactflow',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/BaseStyle`,
        title: 'BaseStyle \u2192',
        imageSrc: '/reactflow/img_1.png',
        description: 'BaseStyle',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/CollisionDetection`,
        title: 'CollisionDetection \u2192',
        imageSrc: '/reactflow/img_6.png',
        description: 'CollisionDetection',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/ContextualZoom`,
        title: 'ContextualZoom \u2192',
        imageSrc: '/reactflow/img_2.png',
        description: 'ContextualZoom',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/CustomConnectionline`,
        title: 'CustomConnectionline \u2192',
        imageSrc: '/reactflow/img_3.png',
        description: 'CustomConnectionline',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/CustomEdges`,
        title: 'CustomEdges \u2192',
        imageSrc: '/reactflow/img_8.png',
        description: 'CustomEdges',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/CustomNodes`,
        title: 'CustomNodes \u2192',
        imageSrc: '/reactflow/img_7.png',
        description: 'CustomNodes',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/CustomNodes2`,
        title: 'CustomNodes2 \u2192',
        imageSrc: '/reactflow/img_9.png',
        description: 'CustomNodes2',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/DagreTree`,
        title: 'DagreTree \u2192',
        imageSrc: '/reactflow/img_10.png',
        description: 'DagreTree',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/DeleteEdgeonDrop`,
        title: 'DeleteEdgeonDrop \u2192',
        imageSrc: '/reactflow/img_11.png',
        description: 'DeleteEdgeonDrop',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/DownloadImage`,
        title: 'DownloadImage \u2192',
        imageSrc: '/reactflow/img_12.png',
        description: 'DownloadImage',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/DragAndDrop`,
        title: 'DragAndDrop \u2192',
        imageSrc: '/reactflow/img_14.png',
        description: 'DragAndDrop',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/DragHandle`,
        title: 'DragHandle \u2192',
        imageSrc: '/reactflow/img_15.png',
        description: 'DragHandle',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/EasyConnect`,
        title: 'EasyConnect \u2192',
        imageSrc: '/reactflow/img_16.png',
        description: 'EasyConnect',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/EdgeLabelRenderer`,
        title: 'EdgeLabelRenderer \u2192',
        imageSrc: '/reactflow/img_17.png',
        description: 'EdgeLabelRenderer',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/EdgeMarkers`,
        title: 'EdgeMarkers \u2192',
        imageSrc: '/reactflow/img_18.png',
        description: 'EdgeMarkers',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/EdgeTypes`,
        title: 'EdgeTypes \u2192',
        imageSrc: '/reactflow/img_19.png',
        description: 'EdgeTypes',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/EdgeWithButton`,
        title: 'EdgeWithButton \u2192',
        imageSrc: '/reactflow/img_20.png',
        description: 'EdgeWithButton',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/FeatureOverview`,
        title: 'FeatureOverview \u2192',
        imageSrc: '/reactflow/img_21.png',
        description: 'FeatureOverview',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/FloatingEdges`,
        title: 'FloatingEdges \u2192',
        imageSrc: '/reactflow/img_22.png',
        description: 'FloatingEdges',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/flow-edit`,
        title: 'flow-edit \u2192',
        imageSrc: '/reactflow/img_1.png',
        description: 'flow-edit',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/Hidden`,
        title: 'Hidden \u2192',
        imageSrc: '/reactflow/img_23.png',
        description: 'Hidden',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/HorizontalFlow`,
        title: 'HorizontalFlow \u2192',
        imageSrc: '/reactflow/img_24.png',
        description: 'HorizontalFlow',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/InteractionProps`,
        title: 'InteractionProps \u2192',
        imageSrc: '/reactflow/img_25.png',
        description: 'InteractionProps',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/Intersections`,
        title: 'Intersections \u2192',
        imageSrc: '/reactflow/img_26.png',
        description: 'Intersections',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/LightDarkMode`,
        title: 'LightDarkMode \u2192',
        imageSrc: '/reactflow/img_27.png',
        description: 'LightDarkMode',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/NodeResizer`,
        title: 'NodeResizer \u2192',
        imageSrc: '/reactflow/img_28.png',
        description: 'NodeResizer',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/PanningandZooming`,
        title: 'PanningandZooming \u2192',
        imageSrc: '/reactflow/img_29.png',
        description: 'PanningandZooming',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/ProximityConnect`,
        title: 'ProximityConnect \u2192',
        imageSrc: '/reactflow/img_30.png',
        description: 'ProximityConnect',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/react-flow`,
        title: 'react-flow \u2192',
        imageSrc: '/reactflow/img_31.png',
        description: 'react-flow',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/react-intersection-observer`,
        title: 'react-intersection-observer \u2192',
        imageSrc: '/reactflow/img_32.png',
        description: 'react-intersection-observer',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/ReactFlowProvider`,
        title: 'ReactFlowProvider \u2192',
        imageSrc: '/reactflow/img_33.png',
        description: 'ReactFlowProvider',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/ResizeandRotate`,
        title: 'ResizeandRotate \u2192',
        imageSrc: '/reactflow/img_34.png',
        description: 'ResizeandRotate',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/SaveAndRestore`,
        title: 'SaveAndRestore \u2192',
        imageSrc: '/reactflow/img_35.png',
        description: 'SaveAndRestore',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/SimpleFloatingEdges`,
        title: 'SimpleFloatingEdges \u2192',
        imageSrc: '/reactflow/img_36.png',
        description: 'SimpleFloatingEdges',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },    {
        href: `${pathgroup}/Stress`,
        title: 'Stress \u2192',
        imageSrc: '/reactflow/img_37.png',
        description: 'Stress',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },    {
        href: `${pathgroup}/SubFlow`,
        title: 'SubFlow \u2192',
        imageSrc: '/reactflow/img_38.png',
        description: 'SubFlow',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },    {
        href: `${pathgroup}/SubFlows`,
        title: 'SubFlows \u2192',
        imageSrc: '/reactflow/img_39.png',
        description: 'SubFlows',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },    {
        href: `${pathgroup}/TouchDevice`,
        title: 'TouchDevice \u2192',
        imageSrc: '/reactflow/img_40.png',
        description: 'TouchDevice',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },    {
        href: `${pathgroup}/ZoomTransitions`,
        title: 'ZoomTransitions \u2192',
        imageSrc: '/reactflow/img_41.png',
        description: 'ZoomTransitions',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/UncontrolledFlow`,
        title: 'UncontrolledFlow \u2192',
        imageSrc: '/reactflow/img_42.png',
        description: 'UncontrolledFlow',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/UpdatableEdge`,
        title: 'UpdatableEdge \u2192',
        imageSrc: '/reactflow/img_43.png',
        description: 'UpdatableEdge',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/UpdateNode`,
        title: 'UpdateNode \u2192',
        imageSrc: '/reactflow/img_44.png',
        description: 'UpdateNode',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/useReactFlow`,
        title: 'useReactFlow \u2192',
        imageSrc: '/reactflow/img_45.png',
        description: 'useReactFlow',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/UsingaStateManagementLibrary`,
        title: 'UsingaStateManagementLibrary \u2192',
        imageSrc: '/reactflow/img_46.png',
        description: 'UsingaStateManagementLibrary',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/Validation`,
        title: 'Validation \u2192',
        imageSrc: '/reactflow/img_47.png',
        description: 'Validation',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },

];
