const pathgroup = '/reactflow';

export const ReactFlowLists = [
    {
        href: `${pathgroup}/AddNodeOnEdgeDrop`,
        title: 'github \u2192',
        imageSrc: '/myLists/img.png',
        description: 'reactflow',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/BaseStyle`,
        title: 'github \u2192',
        imageSrc: '/myLists/img.png',
        description: 'BaseStyle',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/CollisionDetection`,
        title: 'github \u2192',
        imageSrc: '/myLists/img.png',
        description: 'CollisionDetection',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/ContextualZoom`,
        title: 'github \u2192',
        imageSrc: '/myLists/img.png',
        description: 'ContextualZoom',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/CustomConnectionline`,
        title: 'CustomConnectionline \u2192',
        imageSrc: '/myLists/img.png',
        description: 'CustomConnectionline',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/CustomEdges`,
        title: 'CustomEdges \u2192',
        imageSrc: '/myLists/img.png',
        description: 'CustomEdges',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/CustomNodes`,
        title: 'CustomNodes \u2192',
        imageSrc: '/myLists/img.png',
        description: 'CustomNodes',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/CustomNodes2`,
        title: 'CustomNodes2 \u2192',
        imageSrc: '/myLists/img.png',
        description: 'CustomNodes2',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/DagreTree`,
        title: 'DagreTree \u2192',
        imageSrc: '/myLists/img.png',
        description: 'DagreTree',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/DeleteEdgeonDrop`,
        title: 'DeleteEdgeonDrop \u2192',
        imageSrc: '/myLists/img.png',
        description: 'DeleteEdgeonDrop',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/DownloadImage`,
        title: 'DownloadImage \u2192',
        imageSrc: '/myLists/img.png',
        description: 'DownloadImage',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/DragAndDrop`,
        title: 'DragAndDrop \u2192',
        imageSrc: '/myLists/img.png',
        description: 'DragAndDrop',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/DragHandle`,
        title: 'DragHandle \u2192',
        imageSrc: '/myLists/img.png',
        description: 'DragHandle',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/EasyConnect`,
        title: 'EasyConnect \u2192',
        imageSrc: '/myLists/img.png',
        description: 'EasyConnect',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/EdgeLabelRenderer`,
        title: 'EdgeLabelRenderer \u2192',
        imageSrc: '/myLists/img.png',
        description: 'EdgeLabelRenderer',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/EdgeMarkers`,
        title: 'EdgeMarkers \u2192',
        imageSrc: '/myLists/img.png',
        description: 'EdgeMarkers',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/EdgeTypes`,
        title: 'EdgeTypes \u2192',
        imageSrc: '/myLists/img.png',
        description: 'EdgeTypes',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/EdgeWithButton`,
        title: 'EdgeWithButton \u2192',
        imageSrc: '/myLists/img.png',
        description: 'EdgeWithButton',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/FeatureOverview`,
        title: 'FeatureOverview \u2192',
        imageSrc: '/myLists/img.png',
        description: 'FeatureOverview',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/FloatingEdges`,
        title: 'FloatingEdges \u2192',
        imageSrc: '/myLists/img.png',
        description: 'FloatingEdges',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/flow-edit`,
        title: 'flow-edit \u2192',
        imageSrc: '/myLists/img.png',
        description: 'flow-edit',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/Hidden`,
        title: 'Hidden \u2192',
        imageSrc: '/myLists/img.png',
        description: 'Hidden',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/HorizonalFlow`,
        title: 'HorizonalFlow \u2192',
        imageSrc: '/myLists/img.png',
        description: 'HorizonalFlow',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/InteractionProps`,
        title: 'InteractionProps \u2192',
        imageSrc: '/myLists/img.png',
        description: 'InteractionProps',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/Intersections`,
        title: 'Intersections \u2192',
        imageSrc: '/myLists/img.png',
        description: 'Intersections',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/LightDarkMode`,
        title: 'LightDarkMode \u2192',
        imageSrc: '/myLists/img.png',
        description: 'LightDarkMode',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/NodeResizer`,
        title: 'NodeResizer \u2192',
        imageSrc: '/myLists/img.png',
        description: 'NodeResizer',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/PanningandZooming`,
        title: 'PanningandZooming \u2192',
        imageSrc: '/myLists/img.png',
        description: 'PanningandZooming',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/ProximityConnect`,
        title: 'ProximityConnect \u2192',
        imageSrc: '/myLists/img.png',
        description: 'ProximityConnect',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/react-flow`,
        title: 'react-flow \u2192',
        imageSrc: '/myLists/img.png',
        description: 'react-flow',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/react-intersection-observer`,
        title: 'react-intersection-observer \u2192',
        imageSrc: '/myLists/img.png',
        description: 'react-intersection-observer',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/ReactFlowProvider`,
        title: 'ReactFlowProvider \u2192',
        imageSrc: '/myLists/img.png',
        description: 'ReactFlowProvider',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/ResizeandRotate`,
        title: 'ResizeandRotate \u2192',
        imageSrc: '/myLists/img.png',
        description: 'ResizeandRotate',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/`,
        title: ' \u2192',
        imageSrc: '/myLists/img.png',
        description: '',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/SaveAndRestore`,
        title: 'SaveAndRestore \u2192',
        imageSrc: '/myLists/img.png',
        description: 'SaveAndRestore',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
    {
        href: `${pathgroup}/SimpleFloatingEdges`,
        title: 'SimpleFloatingEdges \u2192',
        imageSrc: '/myLists/img.png',
        description: 'SimpleFloatingEdges',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },    {
        href: `${pathgroup}/Stress`,
        title: 'Stress \u2192',
        imageSrc: '/myLists/img.png',
        description: 'Stress',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },    {
        href: `${pathgroup}/SubFlow`,
        title: 'SubFlow \u2192',
        imageSrc: '/myLists/img.png',
        description: 'SubFlow',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },    {
        href: `${pathgroup}/SubFlows`,
        title: 'SubFlows \u2192',
        imageSrc: '/myLists/img.png',
        description: 'SubFlows',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },    {
        href: `${pathgroup}/TouchDevice`,
        title: 'TouchDevice \u2192',
        imageSrc: '/myLists/img.png',
        description: 'TouchDevice',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },    {
        href: `${pathgroup}/ZoomTransitions`,
        title: 'ZoomTransitions \u2192',
        imageSrc: '/myLists/img.png',
        description: 'ZoomTransitions',
        tags: ['reactflow', 'react', 'typescript', 'nextjs'],
    },
];
