import Head from 'next/head'
import styles from 'src/styles/Home.module.css'
import {Footer} from "src/components/Footer"
import {Main} from "src/components/Main";
import {Header} from "src/components/Header";

const About = (props: any) => {

    return (
        <div className={styles.container}>
            <Head>
                <title>About Page</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/public/favicon.ico"/>
            </Head>
            <Header/>

            <button onClick={props.handleClick}>カウントアップ</button>
            <button onClick={props.handleDisplay}>{props.isShow ? '非表示' : '表示'}</button>
            <button onClick={props.handleAdd}>配列追加</button>
            <input type="text"
                   value={props.text}
                   onChange={props.handleChanged}
            />
            <div>{props.text}</div>
            {props.isShow ? <h1>{props.count}</h1> : null}
            {props.isShow ? <h1>{props.doubleCount}</h1> : null}
            <ul>
                {props.array.map((item: string | number | null, index: number) => {
                    return <li key={index}>{item}</li>
                })}
            </ul>
            <Main page={'about'}/>
            <Footer/>
        </div>
    )
}

export default About;
