import Head from 'next/head'
import styles from 'src/styles/Home.module.css'
import {Footer} from "src/components/Footer"
import {Main} from "src/components/Main";
import {Header} from "src/components/Header";

export default function About(props: any) {
    const {count, isShow, handleClick, handleDisplay, text, array, handleChanged, handleAdd} = props

    return (
        <div className={styles.container}>
            <Head>
                <title>About Page</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/public/favicon.ico"/>
            </Head>
            <Header></Header>

            <button onClick={handleClick}>カウントアップ</button>
            <button onClick={handleDisplay}>{isShow ? '非表示' : '表示'}</button>
            <button onClick={handleAdd}>配列追加</button>
            <input type="text"
                   value={text}
                   onChange={handleChanged}
            />
            <div>{text}</div>
            {isShow ? <h1>{count}</h1> : null}
            <ul>
                {array.map((item: string | number | null, index: number) => {
                    return <li key={index}>{item}</li>
                })}
            </ul>
            <Main page={'about'}/>
            <Footer/>
        </div>
    )
}
