import Head from 'next/head'
import styles from 'src/styles/Home.module.css'
import {Footer} from "src/components/Footer"
import React from "react";
import {Main} from "src/components/Main";
import {Header} from "src/components/Header";
import {Links} from "../components/Links";


export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>About Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>
            <Header></Header>
            <Main page={'about'} />
            <Footer />
        </div>
    )
}
