import Head from 'next/head'
import {Footer} from "src/components/Footer"
import {Main} from "src/components/Main"
import {Header} from "src/components/Header"
import styled from 'styled-components';

const Container = styled.div`
    padding: 0 2rem;
`;

const Index2 = (props: any) => {
    return (
        <Container>
            <Head>
                <title>Index Page</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/public/favicon.ico"/>
            </Head>
            <Header></Header>

            <button onClick={props.handleClick}>ぼたん</button>
            <button onClick={props.handleDisplay}>{props.isShow ? '非表示' : '表示'}</button>

            <button onClick={props.handleAdd}>配列追加</button>
            <input type="text"
                   value={props.text}
                   onChange={props.handleChanged}
            />
            {props.isShow ? <h1>{props.count}</h1> : null}
            <div>{props.text}</div>
            <ul>
                {props.array.map((item: string | number | null, index: number) => {
                    return <li key={index}>{item}</li>
                })}
            </ul>


            <Main page='index'/>
            <Footer/>
        </Container>
    )
}

export default Index2;
