import Head from 'next/head'
import {Footer} from "src/components/Footer"
import {Main} from "src/components/Main"
import {Header} from "src/components/Header"
import React, {useCallback, useEffect} from "react";
import styled from 'styled-components';
import Link from "next/link";

const Container = styled.div`
    padding: 0 2rem;
`;

export default function Home() {
    const [count, setFoo] = React.useState(1)

    // useCallbackは、再生性されない関数を作成する。
    const handleClick = useCallback(() => {
        console.log(count)
        if (count < 10) {
            setFoo(count => count + 1)
        }

        // setFoo(count => count + 1)
        // setFoo(count => count + 1)
        // setFoo(foo + 1)
        // 関数との違いは、こっちは直接値を渡しているので、
        // この時点で値が決まっているので、useEffectの中で値を参照すると、
        // この時点での値が参照される。
    },[count]);

    // useEffectは、レンダリング後に実行される。
    useEffect(() => {
        console.log('useEffect')
        document.body.style.backgroundColor = 'lightblue'

        return () => {
            console.log('useEffect return')
            document.body.style.backgroundColor = 'lightgreen'
        }
    }, [])

    return (
        <Container>
            <Head>
                <title>Index Page</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/public/favicon.ico"/>
            </Head>
            <Header></Header>
            <h1>{count}</h1>
            <button
                onClick={handleClick}
            >
                ぼたん
            </button>
            <Main page='index'/>
            <Footer/>
        </Container>
    )
}
