import Head from 'next/head'
import {Footer} from "src/components/Footer"
import {Main} from "src/components/Main"
import {Header} from "src/components/Header"
import React from "react";
import styled from 'styled-components';

const Container = styled.div`
    padding: 0 2rem;
`;

export default function Home() {
    return (
        <Container>
            <Head>
                <title>Index Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>
            <Header></Header>
            <Main page='index' />
            <Footer />
        </Container>
    )
}
